- name: Install snapd (Debian/Ubuntu)
  apt:
    name: snapd
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install snapd (Red Hat/CentOS)
  package:
    name: snapd
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install MicroK8s
  snap:
    name: microk8s
    state: present

- name: Add user to MicroK8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: Make sure .kube directory exists
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy kubeconfig file
  copy:
    src: /var/snap/microk8s/current/credentials/client.config
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Make sure MicroK8s is running
  shell: microk8s status --wait-ready
  register: microk8s_status
  until: microk8s_status.stdout.find('microk8s is running') != -1
  retries: 10
  delay: 10