- name: Update system (Debian/Ubuntu)
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Update system (Red Hat/CentOS)
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS'