
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "master-01" do |vm1|
    vm1.vm.hostname = "master-01"
    vm1.vm.network "private_network", ip: "192.168.33.10"
    vm1.vm.provision "shell", path: "bootstrap.sh"
  end

  config.vm.define "worker-01" do |vm2|
    vm2.vm.hostname = "worker-01"
    vm2.vm.network "private_network", ip: "192.168.33.100"
    vm2.vm.provision "shell", path: "bootstrap.sh"
  end
end
